export const GAME_CONFIG = {
  initialLength: 10,
  minimumLength: 10,
  maximumLength: 100,
  selfCollisionMinimumLength: 15,
  quizOrbInterval: 10,
  correctAnswerScoreBonus: 10,
  correctAnswerBoostSeconds: 5,
  incorrectAnswerScorePenalty: 5,
  incorrectAnswerLengthPenalty: 5,
  incorrectAnswerSlowdownSeconds: 3,
  minimumScore: 0,
  baseSpeed: 15,
  manualBoostSpeed: 30,
  quizBoostMultiplier: 1.3,
  slowdownMultiplier: 0.6,
  turnSpeed: Math.PI * 3,
  segmentSpacing: 0.5,
  orbCollectionRadius: 2,
  selfCollisionRadius: 0.9,
  selfCollisionIgnoredSegments: 5,
  hazardActivationOrbs: 7,
  hazardRadius: 3.5,
  hazardActivationGraceSeconds: 2,
  hazardPlayerSpawnClearance: 4,
  hazardOrbSpawnClearance: 2,
  hazardSpawnAttempts: 12,
  simulationRate: 60,
  snapshotRate: 20,
  inputRate: 30,
} as const;

export const CHAPTER_IDS = [3, 4, 5, 6, 7, 8, 9, 10] as const;
